let playerx = 300;
let playery = 500;
let playerW = 60;
let pipey = -50;
let holeW;
let holeX;
let hit = false;
let pipespeed = 3;
let starpossition = [];
let time = false;
let starX;
let starY;
let starR;
let starMaxR = 8;
let starMaxSpeed = 2.8;
let flameState;
let crashR = 10;
let pointX;
let pointY;
let pointR = 10;
let laser = false;
let Raylen = 100;
let gameState = 0;
let Highscore = 95526;
let finalTime;
